version: 2.1

jobs:
  "test":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-latest-node-with-gcloud:0.0.1
    steps:
      - checkout
      - run: npm install
      - run:
          name: Unit Testing
          command: |
            npm run test

  "deploy_prod":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run:
          name: Deploy to production
          environment:
            GCP_PROJECT: rvaserver2
          command: |
            gcloud auth activate-service-account 452091732215@developer.gserviceaccount.com --key-file private-keys/storage-server/rva-media-library-ce0d2bd78b54.json
            npm run deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - "test":
      - "deploy_prod":
          requires:
            - test
          filters:
            branches:
              only: master
