# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment Workflow

on:
  push:
    branches: [ stage/**, fix/**, feature/**, master ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    env:
      GCF_FUNCTION_NAME_CHECKER: ${{ secrets.GCF_FUNCTION_NAME_CHECKER }}
      GCF_FUNCTION_NAME_SUBMITTER: ${{ secrets.GCF_FUNCTION_NAME_SUBMITTER }}

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
       service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
       export_default_credentials: true

    - name: Run tests
      run: |
        npm ci
        npm test

    - name: Deploy Staging
      if: ${{ github.ref != 'refs/heads/master' }}
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT_TEST }}
      run: |
        npm run deploy

    - name: Deploy Prod
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT_PROD }}
      run: npm run deploy
